### PR TITLE
Setup docs

### PR DESCRIPTION
**Pull request by patcon**
Don't really need to merge this, but just wanted to show little things I came
across while trying to get it to work. I actually thinking I probably went
about it the wrong way, but perhaps you could put me on track? :)

### CODE REVIEW

**Comment by dougestey** [comment]
I definitely need to get docs updated, and I'll do that tonight. In the meantime, I merged a couple of fixes to bower config that should allow you to build properly.

Speaking of the build - you do need to npm install -g cordova to get the CLI. Then once you've updated bower, run (from the project root):

```
$ cordova platform add browser
$ cordova emulate browser
```

Other platforms you can add & build include ios (on a Mac) & android.

Good luck, and I'll update more tonight. If you want to modify your PR to reflect this new info, I'll happily merge it!

**Comment by patcon** [comment]
thanks doug! i think I got it going as expected. Let me know if anything's missing, or feel free to checkout my branch and add anything else for a local merge

Am I right to assume that the platforms/plugins dirs are gitignored at this juncture?

**Comment by dougestey** [comment]
Yes, platforms and plugins should be ignored. Great update Pat. Merged & closed.

**Comment by patcon** [comment]
haha it helps that, in regards to cordova...

i have no idea what i'm doing

:)

**Pull request merged**
